tidy up the code
ShimShtein/foreman_build_history pull request #4
Opened 2017-02-21 19:32 UTC by timogoebel

2017-02-22 09:07 UTC, ShimShtein requested changes
Thank you for tidying up the plugin a bit, I really appreciate it! If you don't mind, I have some change proposals inline.

2017-02-22 09:07 UTC, ShimShtein commented on foreman_build_history.gemspec
> +  s.homepage    = 'http://github.com/theforeman/foreman_build_history'
In the meantime it's in my repo, `https://github.com/ShimShtein/foreman_build_history`.
Unless you already want to move it to core ;)

2017-02-22 09:07 UTC, ShimShtein commented on README.md
> +See [Plugins install instructions](https://theforeman.org/plugins/)
This plugin is not packaged, the only way to install it right now is through gems. Can we change the URL to more specific one: `https://theforeman.org/plugins/#2.3AdvancedInstallationfromGems`?

2017-02-22 09:07 UTC, ShimShtein commented on lib/foreman_build_history/facet.rb
>  Facets.register(BuildHistoryFacet) do
We can get rid of the `do..end` block entirely.
At least until we want to add a per-host history tab.

2017-02-22 09:21 UTC, timogoebel commented on foreman_build_history.gemspec
> +  s.homepage    = 'http://github.com/theforeman/foreman_build_history'
I do suggest moving it to the foreman.org - it increased visibility and it's easier to get jenkins integration. In addition permissions management is better.

But I'll change this for now.

2017-02-22 09:21 UTC, timogoebel commented on README.md
> +See [Plugins install instructions](https://theforeman.org/plugins/)
I do want to package it once it's ready for a release.

2017-02-22 09:23 UTC, timogoebel commented on lib/foreman_build_history/facet.rb
>  Facets.register(BuildHistoryFacet) do
Can you already add a tab to the host show page through facets? I tried with pagelets but the required mount points were missing as well.

2017-02-22 10:50 UTC, ShimShtein commented on lib/foreman_build_history/facet.rb
>  Facets.register(BuildHistoryFacet) do
Not exactly through facets, but through initializer:
https://github.com/theforeman/foreman/blob/develop/config/initializers/puppet.rb#L3

2017-02-22 10:55 UTC, ShimShtein commented on foreman_build_history.gemspec
> +  s.homepage    = 'http://github.com/theforeman/foreman_build_history'
I am all for it, but I would like to add proper testing and rubocop before we do it.

2017-02-22 12:22 UTC, timogoebel commented
@ShimShtein : Thanks, I have addressed your comments.

2017-02-26 10:31 UTC, ShimShtein approved these changes

2017-02-26 10:32 UTC, ShimShtein commented
Thanks @timogoebel!

Merged as bd81a64b9baa70568a537687bf603f1727ff2226

2017-02-26 10:32 UTC, closed without merging